from cybersportruparser.api import CybersportRuApi as CRA

def run_teams_test():
    print("Testing teams parser")
    cra = CRA()
    teams = cra.get_teams()
    print("Testing: any", teams)
    teams = cra.get_teams(discipline="dota2")
    print("Testing: dota2", teams)
    teams = cra.get_teams(discipline="cs-go")
    print("Testing: cs-go", teams)
    teams = cra.get_teams(discipline="lol")
    print("Testing: lol", teams)
    teams = cra.get_teams(discipline="quake-champions")
    print("Testing: quake-champions", teams)
    teams = cra.get_teams(discipline="heartstone")
    print("Testing: heartstone", teams)
    teams = cra.get_teams(discipline="sc2")
    print("Testing: sc2", teams)
    teams = cra.get_teams(discipline="hots")
    print("Testing: hots", teams)
    teams = cra.get_teams(discipline="overwatch")
    print("Testing: overwatch", teams)

def run_gamers_test():
    print("Testing gamers parser")
    cra = CRA()
    gamers = cra.get_gamers()
    print("Testing: any", gamers)
    teams = cra.get_gamers(discipline="dota2")
    print("Testing: dota2", teams)
    teams = cra.get_gamers(discipline="cs-go")
    print("Testing: cs-go", teams)
    teams = cra.get_gamers(discipline="lol")
    print("Testing: lol", teams)
    teams = cra.get_gamers(discipline="quake-champions")
    print("Testing: quake-champions", teams)
    teams = cra.get_gamers(discipline="heartstone")
    print("Testing: heartstone", teams)
    teams = cra.get_gamers(discipline="sc2")
    print("Testing: sc2", teams)
    teams = cra.get_gamers(discipline="hots")
    print("Testing: hots", teams)
    teams = cra.get_gamers(discipline="overwatch")
    print("Testing: overwatch", teams)

run_teams_test()
run_gamers_test()